[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 50

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]

[chains]
ingestor = "block_ingestor_node"

[chains.endurance-mainnet]
provider = [
    { label = "endurance-mainnet", url = "https://rpc-endurance.fusionist.io", features = [] }
]
shard = "primary"
